title: This is my first course
tagline: A brand new course on Learning Lab
description: To create branch and PR
template:
  repo: data-solutions-training-user
  name: data-solutions-training
  description: Data Solution Training Repository
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
    action_id: '10'
steps:
  - title: Create a branch
    description: >-
      To work on a new building block or update an existing one, you need to
      create a branch
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
