title: This is my first course
tagline: A brand new course on Learning Lab
description: To create branch and PR
template:
  repo: this-is-my-first-course-template
  name: this-is-my-first-course
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
